#ifndef COSMOGRAPHER_KEYHOLECONSTANTS_H
#define COSMOGRAPHER_KEYHOLECONSTANTS_H

#define HEADER_SIZE 4
#define LED_COUNT (64 * 64)
#define PACKET_SIZE (HEADER_SIZE + LED_COUNT * 3)
#define BAUDRATE (1 * 1000 * 1000)
#define FRAME_RATE 16000

#endif //COSMOGRAPHER_KEYHOLECONSTANTS_H
