# general
axiomologySize: 10
maxGlimmers: 10000
essentiaSize: 2048
# lumion count should be < essentia size and % = 0
lumionCount: 2048
baseGlimmerSize: 0.08

# endpoints
percipiaEndpoint: ipc:///tmp/percipia
essentiaEndpoint: ipc:///tmp/analogorium
volitiaEndpoint: tcp://volitia:44440

# fullscreen
percipiaWidth: 200
percipiaHeight: 200
latticeInitialHue: 100
latticeInitialSaturation: 100
latticeInitialLightness: 100
