# general
axiomologySize: 10
maxGlimmers: 10000
lumionCount: 2048

# endpoints
percipiaEndpoint: ipc:///tmp/percipia
essentiaEndpoint: ipc:///tmp/analogorium
volitiaEndpoint: tcp://volitia:44440

# fullscreen
percipiaWidth: 192
percipiaHeight: 108
latticeInitialHue: 0
latticeInitialSaturation: 0
latticeInitialLightness: 0
