# general
axiomologySize: 10
illuminatorThreadCount: 8
maxGlimmers: 15000

# sockets
palantirEndpoint: ipc:///tmp/cosmographer
essentiaEndpoint: ipc:///tmp/analogorium
#essentiaEndpoint: tcp://10.42.0.1:44444
volitiaEndpoint: tcp://volitia:44440

# lattice
# fullscreen
latticeWidth: 192
latticeHeight: 108

# cube
#latticeWidth: 100
#latticeHeight: 100

latticeInitialHue: 0
latticeInitialSaturation: 0
latticeInitialLightness: 100
#latticeInitialLightness: 0

# mesh
#lumionCount: 7400
lumionCount: 4097
#lumionCount: 2073600

# value bounds depend on mesh and signal size
# lumionPlacement: 0.2
lumionPlacement: 0.6
