# general
axiomologySize: 10
illuminatorThreadCount: 8
maxGlimmers: 100000

# sockets
# remote palantir
#palantirEndpoint: tcp://10.42.0.1:44447
palantirEndpoint: ipc:///tmp/cosmographer
essentiaEndpoint: ipc:///tmp/analogorium
volitiaEndpoint: tcp://volitia:44440
#volitiaEndpoint: tcp://192.168.22.161:44440

# lattice
# fullscreen
#latticeWidth: 192
#latticeHeight: 108

# cube
latticeWidth: 200
latticeHeight: 200

latticeInitialHue: 0
latticeInitialSaturation: 0
latticeInitialLightness: 0

# mesh
#lumionCount: 7400
lumionCount: 4097
#lumionCount: 2073600

# value bounds depend on mesh and signal size
# lumionPlacement: 0.2
lumionPlacement: 1
