# general
axiomologySize: 10
illuminatorThreadCount: 8
maxGlimmers: 5000

# sockets
palantirEndpoint: ipc:///tmp/cosmographer
essentiaEndpoint: ipc:///tmp/analogorium
volitiaEndpoint: tcp://volitia:44440

# lattice
latticeWidth: 96
latticeHeight: 54
latticeInitialHue: 0
latticeInitialSaturation: 0
latticeInitialLightness: 100

# mesh
#lumionCount: 7400
lumionCount: 4097
#lumionCount: 2073600

# value bounds depend on mesh and signal size
lumionPlacement: 0.2
