# general
axiomologySize: 10
illuminatorThreadCount: 8
maxGlimmers: 10000

# sockets
palantirEndpoint: tcp://0.0.0.0:44447i
#palantirEndpoint: ipc:///tmp/cosmographer
essentiaEndpoint: ipc:///tmp/analogorium
#essentiaEndpoint: tcp://vinculus_chateau-rose:44447
#essentiaEndpoint: tcp://10.0.0.187:44447
volitiaEndpoint: tcp://10.0.0.85:44440
#volitiaEndpoint: tcp://192.168.22.161:44440

###########@reboot cd /root/cosmographer && ./cmake-build-release-keyhole_1/cosmographer
# lattice #
###########

# fullscreen
#latticeWidth: 192
#latticeHeight: 108
#lumionPlacement: 1

# square
latticeWidth: 200
latticeHeight: 200
lumionPlacement: 3

# keyhole
#latticeWidth: 20
#latticeHeight: 74
#lumionPlacement: 0.05

latticeInitialHue: 0
latticeInitialSaturation: 0
latticeInitialLightness: 0

# mesh
#lumionCount: 4097
lumionCount: 2048
