# general
axiomologySize: 10
illuminatorThreadCount: 4
maxGlimmers: 50000

# sockets
palantirEndpoint: ipc:///tmp/cosmographer
essentiaEndpoint: ipc:///tmp/analogorium
volitiaEndpoint: tcp://volitia:44440

# lattice
latticeWidth: 100
latticeHeight: 74
latticeInitialHue: 0
latticeInitialSaturation: 0
latticeInitialLightness: 100

# mesh
#lumionCount: 7400
lumionCount: 4097

# value bounds depend on mesh and signal size
lumionPlacement: 0.2
