# general
# 0 = keyhole
# 1 = palantir
vantage_type: 0

# tick interval
luciferon_tick_interval: 15000

# sockets
luciferon_endpoint: tcp://0.0.0.0:44400
palantir_endpoint: ipc:///tmp/cosmographer
analogorium_endpoint: ipc:///tmp/analogorium
volitia_endpoint: tcp://volitia:44440

# lattice
lattice_width: 60
lattice_height: 74
