#ifndef COSMOGRAPHER_KEYHOLECONSTANTS_H
#define COSMOGRAPHER_KEYHOLECONSTANTS_H

#define HEADER_SIZE 4
#define LED_COUNT (74 * 20)
#define PACKET_SIZE (HEADER_SIZE + LED_COUNT * 3)
#define BAUDRATE (5 * 1000 * 1000)

#endif //COSMOGRAPHER_KEYHOLECONSTANTS_H
