#ifndef COSMOGRAPHER_DRAGONCURVESYSTEM_H
#define COSMOGRAPHER_DRAGONCURVESYSTEM_H

namespace cosmographer {

enum DragonCurveRunology {
    advance,
    rotateLeftQuarter,
    rotateRightQuarter
};

vec<DragonCurveRunology> dragonCurveRunes = {advance, rotateLeftQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateLeftQuarter, advance, rotateLeftQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateLeftQuarter, advance, rotateRightQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance,
                                             rotateLeftQuarter, advance, rotateLeftQuarter, advance, rotateRightQuarter,
                                             advance, rotateRightQuarter, advance, rotateLeftQuarter, advance,
                                             rotateRightQuarter, advance, rotateRightQuarter, advance};

}

#endif //COSMOGRAPHER_DRAGONCURVESYSTEM_H
