#ifndef COSMOGRAPHER_DRAGONCURVESYSTEM_H
#define COSMOGRAPHER_DRAGONCURVESYSTEM_H

#include "Default.h"

enum DragonCurveSymbols {
    advance,
    rotateLeft,
    rotateRight
};

vec<DragonCurveSymbols> dragonCurveSystem = {DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateLeft,
                                             DragonCurveSymbols::advance,
                                             DragonCurveSymbols::advance, DragonCurveSymbols::rotateRight,
                                             DragonCurveSymbols::advance};

#endif //COSMOGRAPHER_DRAGONCURVESYSTEM_H
