#ifndef COSMOGRAPHER_BINDINGS_H
#define COSMOGRAPHER_BINDINGS_H

// axiom bindings
#define AXIOM(index) paradigm->axioms[index]
#define PALETTE_AXIOM_0 AXIOM(0)
#define LUMION_EXCITATION_AXIOM AXIOM(1)
#define LUMION_DRIFT AXIOM(2)
#define GLIMMER_SIZE_AXIOM AXIOM(3)
#define GLIMMER_COUNT_AXIOM AXIOM(4)
#define EPHEMERA_AXIOM_0 AXIOM(5)
#define EPHEMERA_AXIOM_1 AXIOM(6)
#define EPHEMERA_AXIOM_2 AXIOM(7)
#define WORKSHOP_AXIOM AXIOM(8)
#define HUE_JITTER_AXIOM AXIOM(9)

#endif //COSMOGRAPHER_BINDINGS_H
