#ifndef COSMOGRAPHER_BINDINGS_H
#define COSMOGRAPHER_BINDINGS_H

// axiom bindings
#define AXIOM(index) paradigm->axioms[index]
#define PALETTE_AXIOM_0 AXIOM(0)
#define LUMION_EXCITATION_THRESHOLD_AXIOM AXIOM(1)
#define POPULATION_SIZE_AXIOM AXIOM(2)
#define SIZE_AXIOM AXIOM(3)
#define COUNT_AXIOM AXIOM(4)
#define MUTATION_AXIOM AXIOM(5)
#define SPEED_AXIOM AXIOM(6)
#define LIFESPAN_AXIOM AXIOM(7)
#define BRIGHTNESS_AXIOM AXIOM(8)
#define HUE_JITTER_AXIOM AXIOM(9)

#endif //COSMOGRAPHER_BINDINGS_H
